// Add project imagery and details here; the folder layout adapts automatically.
export const projects = [
  {
    id: 'qetsiyah-eco-park',
    tab: 'QETSIYAH',
    name: 'Qetsiyah Eco Park',
    category: 'WEB DESIGN / DEVELOPMENT',
    archiveDate: 'Archive Assemblage · 2024',
    breadcrumbs: 'INDEX / REGISTRY / ARCHIVE / QETSIYAH',
    description: 'The Qetsiyah Eco Park Web Platform is a modern digital experience designed to showcase Qetsiyah Eco Park as a premier eco-tourism, recreation, dining, and private event destination in Sultan Kudarat.',
    details: 'Beyond showcasing the destination, the platform simplifies how guests plan their visits and send reservations, replacing scattered social media inquiries with a centralized and organized system.',
    overview: {
      p1: 'The Qetsiyah Eco Park Web Platform is a modern digital experience designed to showcase Qetsiyah Eco Park as a premier eco-tourism, recreation, dining, and private event destination in Sultan Kudarat. The platform brings the park’s peaceful and nature-focused atmosphere online, allowing visitors to explore attractions, dining options, event venues, activities, rates, and essential park information through a responsive and visually engaging experience.',
      p2: 'Beyond showcasing the destination, the platform simplifies how guests plan their visits and send reservations, replacing scattered social media inquiries with a centralized and organized system. Built for families, travelers, adventure seekers, diners, and event organizers, the project combines tourism, hospitality, storytelling, and modern web technology to strengthen Qetsiyah Eco Park’s digital presence and help promote tourism in the surrounding region.',
    },
    disciplines: ['Web design', 'UI/UX', 'Development'],
    cover: '/Project%20Images/Qetsiyah%20Eco%20Park.png',
    alt: 'Qetsiyah Eco Park website design',
    gallery: [
      '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-02%20210318.png',
      '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-12%20212019.png',
      '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-12%20212101.png',
      '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-12%20212131.png',
    ],
    images: [
      { src: '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-02%20210318.png', alt: 'Qetsiyah Eco Park website homepage', caption: '01 / Homepage' },
      { src: '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-12%20212019.png', alt: 'Qetsiyah Eco Park features overview', caption: '02 / Features' },
      { src: '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-12%20212101.png', alt: 'Qetsiyah Eco Park events booking section', caption: '03 / Booking' },
      { src: '/Qetsiyah%20Project%20Pictures/Screenshot%202026-09-12%20212131.png', alt: 'Qetsiyah Eco Park park amenities', caption: '04 / Amenities' },
    ],
    link: 'https://github.com/Topor24k/Qetsiyah-Eco-Park',
    artifacts: [
      {
        id: 'q-01',
        title: 'Q-101',
        subtitle: 'Eco Park Digital Interface',
        year: '2024',
        type: 'screen',
        description: 'Immersive landscape interface engineered for Qetsiyah Eco Park. Highlights visitor facilities, sunset vistas, and adventure activities through photographic hierarchy.',
        image: '/Project%20Images/Qetsiyah%20Eco%20Park.png',
        badge: 'INTERFACE',
      },
      {
        id: 'q-02',
        title: 'SPEC-02',
        subtitle: 'Field Specification Sheet',
        year: '2024',
        type: 'document',
        docCategory: 'TECHNICAL DISCLOSURE',
        docNumber: 'DOC // 24-QEP',
        docTitle: 'VISITOR ROUTING & EXPERIENCE FUNNEL',
        docLines: [
          'PROJECT: QETSIYAH ECO PARK',
          'DISCIPLINE: WEB ARCHITECTURE & UI',
          'STATUS: PRODUCTION / VERIFIED',
          'MEDIA CHANNELS: ULTRA-WIDE RESPONSIVE',
          'PERF SCORE: 98/100 LIGHTHOUSE OPTIMIZED',
          'STACK: REACT / MODERN CSS / VITE',
        ],
        description: 'Architectural breakdown of the visitor booking funnel, responsive breakpoints, and asset loading pipeline tuned for high-resolution visual storytelling.',
        badge: 'SPEC SHEET',
      },
      {
        id: 'q-03',
        title: 'LOG-03',
        subtitle: 'Photographic & Field Archive',
        year: '2024',
        type: 'photo',
        docCategory: 'FIELD CAPTURE',
        docNumber: 'LOG // 03-ECO',
        docTitle: 'PROTOTYPE BENCHMARK & TESTING',
        docLines: [
          'TEST MATRIX: MOBILE, DESKTOP, 4K',
          'ACCESSIBILITY: WCAG AA COMPLIANT',
          'INTERACTION: KINETIC HOVER & SMOOTH SCROLL',
        ],
        description: 'Production verification log detailing cross-device viewport responsiveness, accessibility standards, and organic typography pairing.',
        badge: 'FIELD LOG',
      },
    ],
  },
  {
    id: 'jld-marketing',
    tab: 'JLD',
    name: 'JLD Marketing',
    category: 'WEB DESIGN / DEVELOPMENT',
    archiveDate: 'Archive Assemblage · 2024',
    breadcrumbs: 'INDEX / REGISTRY / ARCHIVE / JLD',
    description: 'A marketing website built with TypeScript, delivering a polished brand presence with a modern development stack.',
    details: 'A professional marketing site deployed on Vercel, featuring responsive layouts and performance-optimized TypeScript architecture.',
    overview: {
      p1: 'Archival documentation for JLD Marketing Workspace. The project establishes a robust corporate web presence combining data density with clean visual elegance for marketing operations.',
      p2: 'Developed with TypeScript for strict type integrity and performance predictability. Deployed on Vercel with responsive dashboards, interactive metrics previews, and scalable styling modules.',
    },
    disciplines: ['TypeScript', 'Web design', 'Marketing'],
    cover: '/Project%20Images/JLD.png',
    alt: 'JLD Marketing website design',
    images: [
      { src: '/Project%20Images/JLD.png', alt: 'JLD Marketing website homepage', caption: '01 / Homepage' },
    ],
    link: 'https://jld-two.vercel.app',
    artifacts: [
      {
        id: 'jld-01',
        title: 'J-201',
        subtitle: 'Marketing Workspace Overview',
        year: '2024',
        type: 'screen',
        description: 'Primary marketing overview console built with TypeScript. Features operational cash flow metrics, real-time activity ledgers, and responsive controls.',
        image: '/Project%20Images/JLD.png',
        badge: 'CONSOLE',
      },
      {
        id: 'jld-02',
        title: 'SPEC-02',
        subtitle: 'TypeScript Architecture Spec',
        year: '2024',
        type: 'document',
        docCategory: 'SYSTEM ARCHITECTURE',
        docNumber: 'DOC // 88-JLD',
        docTitle: 'TYPE ENGINE & COMPONENT REGISTRY',
        docLines: [
          'FRAMEWORK: TYPESCRIPT + REACT',
          'DEPLOYMENT: VERCEL EDGE RUNTIME',
          'STATE FLOW: MODULAR COMPONENT HOOKS',
          'BUNDLE TARGET: ES2022 TREE-SHAKEN',
          'AUDIT: STRICT NULL CHECKS ENABLED',
        ],
        description: 'Formal architectural specification sheet documenting TypeScript interfaces, modular design tokens, and edge deployment configuration.',
        badge: 'SPEC SHEET',
      },
      {
        id: 'jld-03',
        title: 'LOG-03',
        subtitle: 'Deployment & Telemetry Log',
        year: '2024',
        type: 'log',
        docCategory: 'RELEASE DISPATCH',
        docNumber: 'LOG // 04-REL',
        docTitle: 'PRODUCTION RELEASE PIPELINE',
        docLines: [
          'PIPELINE: GITHUB ACTIONS CI/CD',
          'ENV: PRODUCTION LIVE CLUSTER',
          'CDN: GLOBAL EDGE CACHE HIT 99.4%',
        ],
        description: 'Telemetry and build verification log confirming automated release pipelines and edge caching benchmarks on Vercel.',
        badge: 'SYSTEM LOG',
      },
    ],
  },
  {
    id: 'odyssey',
    tab: 'ODYSSEY',
    name: 'Odyssey',
    category: 'WEB DESIGN / DEVELOPMENT',
    archiveDate: 'Archive Assemblage · 2024',
    breadcrumbs: 'INDEX / REGISTRY / ARCHIVE / ODYSSEY',
    description: 'A JavaScript-driven web project exploring creative interaction patterns and expressive front-end design.',
    details: 'An experimental project focused on front-end craft, built with vanilla JavaScript for lightweight, responsive experiences.',
    overview: {
      p1: 'Archival folio for Odyssey, an experimental interaction suite exploring kinetic interfaces, micro-animations, and fluid physics in browser environments without heavy external dependencies.',
      p2: 'Crafted with vanilla JavaScript and hardware-accelerated CSS transforms. The objective is to achieve maximum expressive feedback and tactile responsiveness within minimal byte weight.',
    },
    disciplines: ['JavaScript', 'Front-end', 'Interaction'],
    cover: '/Project%20Images/Odyssey.png',
    alt: 'Odyssey project design',
    images: [
      { src: '/Project%20Images/Odyssey.png', alt: 'Odyssey project interface', caption: '01 / Interface' },
    ],
    link: 'https://github.com/Topor24k/Odyssey',
    artifacts: [
      {
        id: 'ody-01',
        title: 'O-301',
        subtitle: 'Interactive Odyssey Canvas',
        year: '2024',
        type: 'screen',
        description: 'Primary interaction viewport for Odyssey, rendering kinetic layouts, organic hover responses, and fluid typography in vanilla JavaScript.',
        image: '/Project%20Images/Odyssey.png',
        badge: 'CANVAS',
      },
      {
        id: 'ody-02',
        title: 'SPEC-02',
        subtitle: 'Interaction Physics Blueprint',
        year: '2024',
        type: 'document',
        docCategory: 'EXPERIMENT BLUEPRINT',
        docNumber: 'DOC // 09-ODY',
        docTitle: 'KINEMATIC TRANSFORMS & TIMING',
        docLines: [
          'ENGINE: VANILLA JS HARDWARE ACCEL',
          'FRAME BUDGET: 120FPS TARGET 60FPS MIN',
          'COMPOSITOR: GPU-LAYERED TRANSLATES',
          'DEP WEIGHT: ZERO THIRD-PARTY RUNTIMES',
        ],
        description: 'Technical document detailing the kinematic equations, easing cubic beziers, and frame budgets implemented for micro-interactions.',
        badge: 'PHYSICS SPEC',
      },
      {
        id: 'ody-03',
        title: 'LOG-03',
        subtitle: 'Frame Rate & Event Benchmarks',
        year: '2024',
        type: 'log',
        docCategory: 'BENCHMARK RUN',
        docNumber: 'LOG // 12-FPS',
        docTitle: 'HARDWARE ACCELERATION AUDIT',
        docLines: [
          'GPU REFLOW: 0 FORCED SYNCHRONOUS',
          'EVENT HANDLERS: PASSIVE CAPTURE',
          'MEMORY FOOTPRINT: < 4.2 MB HEAP',
        ],
        description: 'Benchmark telemetry tracking frame stability, composited paint layers, and memory conservation across intensive interaction loops.',
        badge: 'BENCHMARK',
      },
    ],
  },
]
